spring:
  application:
    name: msvc-gateway
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
    gateway:
      routes:
        - id: cliente-service
          uri: lb://msvc-cliente
          predicates:
            - Path=/api/cliente/**
        - id: elevador-service
          uri: lb://msvc-elevador
          predicates:
            - Path=/api/elevador/**

server:
  port: 6768
  address: 0.0.0.0  # Escuchar en todas las interfaces de red

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Para LAN: cambiar por http://192.168.1.100:8761/eureka
